#!/usr/bin/env node
module.exports = {
    list:[
       {
        "name":"duan-admin-pc",
        "desc":"后台应用框架,基于vue+element",
        "author":"duan"
      },
      {
        "name":"duan-mobile",
        "desc":"移动端应用框架,基于Vant",
        "author":"duan"
    },
    {
      "name":"pc-template",
      "desc":"web端单页应用",
      "author":"duan"
    },
    {
      "name":"duan-react",
      "desc":"H5 React项目基于parcel",
      "author":"duan"
    },
    {
      "name":"webpack-react",
      "desc":"基于webpack创建react项目",
      "author":"duan"
    },
    {
      "name":"rollup-react",
      "desc":"基于rollup创建react项目",
      "author":"duan"
    },
    {
      "name":"parcel-react",
      "desc":"基于rollup创建react项目",
      "author":"duan"
    }
  ]
}
